language: ruby
rvm:
  - 2.2
before_script:
  - rake install
script:
  - awesome_bot
  - awesome_bot bin/assets/test-no-issues
  - awesome_bot bin/assets/test-no-links
  - awesome_bot bin/assets/test-parse --white-list coveralls,travis-ci
  - awesome_bot bin/assets/test-dupe --allow-dupe
  - awesome_bot bin/assets/test-timeout --allow-timeout --set-timeout 1
  - awesome_bot bin/assets/test-timeout-and-redirect --allow-timeout --set-timeout 1 --allow-redirect
  - awesome_bot bin/assets/test-redirect --allow-redirect
  - awesome_bot README.md --allow-dupe --white-list gph.is,giphy,travis-ci.org,codeload,badge,rubydoc,rubygems,circleci
